service: "richpanelassessment"
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  # Lambda functions to handle auth routes
  createUser:
    handler: src/Handlers/AuthHandlers/createUser.handler
    events:
      - httpApi:
          path: /api/v1/auth/signup
          method: POST
  login:
    handler: src/Handlers/AuthHandlers/login.handler
    events:
      - httpApi:
          path: /api/v1/auth/login
          method: POST
  getUser:
    handler: src/Handlers/AuthHandlers/getUser.handler
    events:
      - httpApi:
          path: /api/v1/auth/get-user
          method: GET

  # Handlers for facebook api calls and webhooks
  sendMessage:
    handler: src/Handlers/FacebookApiHandlers/sendMessage.handler
    events:
      - httpApi:
          path: /api/v1/fb/sendMessage
          method: POST

  receiveMessage:
    handler: src/Handlers/FacebookApiHandlers/receivemessageWebhook.handler
    events:
      - httpApi:
          path: /webhook/receiveMessage
          method: POST

  receiveMessageCheck:
    handler: src/Handlers/FacebookApiHandlers/receivemessageWebhookCheck.handler
    events:
      - httpApi:
          path: /webhook/receiveMessage
          method: GET

  websocketHandler:
    handler: src/Handlers/WebsocketHandler/websocketHandler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
